### ISSUE TITLE
Story without -> END 

### ISSUE THREAD

**Issue by floriancargoet** [wildwinter/Ink-Tester#2]
InkTester runs until it reaches an `-> END`.
Some stories don't have an explicit -> END (the end may be handled by the external engine, or maybe the story never ends).
It would be nice to be able to specify a timeout or a max number of turns.

**Comment by wildwinter** [comment]
Another good call @floriancargoet, thank you (and reminded me I hadn't even put in an infinite loop check!). Added --maxSteps. TURNS() is flaky and doesn't seem to cover looping within the same content, so this is simply a count of Continue() for now.
